### ISSUE TITLE
Help generating dlls 

### ISSUE THREAD

**Issue by bootzin** [cimgui/cimnodes#3]
I'm trying to generate cimnodes.dll file to use with another project, but I'm having some trouble doing it.

I saw the makefile in cimgui, and tried making something similar for cimnodes (and cimguizmo, for that matter), but I can't get it to work.
I don't have much experience wit c/c++, so I'm not sure on how to properly solve imgui dependencies.. Should I just include imgui.h and imgui_internals.h in the root folder?

Sorry if this seems simple, but I'm a bit confused as to how to proceed

**Comment by sonoro1234** [comment]
No file needs to be moved at all, just set the include path in cmake or makefile.
The only example I can provide for building is https://github.com/sonoro1234/LuaJIT-ImGui where all cimgui , a backend and related widgets are going to one dll. 

For using with ImGui.NET, this https://github.com/mellinoe/ImGui.NET/pull/218#issuecomment-737815513 is you best advise
